name: Trigger worker deploy using wrangler

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <dev|staging|prod>"
        required: true
        default: "dev"
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: NPM install cache
        # You may pin to the exact commit or the version.
        # uses: c-hive/gha-npm-cache@2de807f96074eec2c36c2d321c20724cd04112dd
        uses: c-hive/gha-npm-cache@v1
      - name: Publish app
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --env ${{ github.event.inputs.environment }}
